version: "3"

services:
  terminusdb:
    image: terminusdb/terminusdb-server:dev
    tty: true
    ports:
      - 6363:6363
    volumes:
      - /home/robin/git/terminusdb/terminusdb-fresh/storage:/app/terminusdb/storage
  web:
    image: openresty/openresty:bullseye
    volumes:
      - ./templates/default.conf.template:/etc/nginx/conf.d/default.conf
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80

  redis:
    image: redis:7
    ports:
      - 6379:6379
